# Generated by Django 6.0.1 on 2026-05-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
